In [2]:
import pandas as pd
import requests, pandas as pd
import xmltodict
import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from datetime import datetime
from sqlalchemy import text

In [3]:
load_dotenv(override=True)
db_user = os.getenv('db_user')
db_password = os.getenv('db_password')
db_host = os.getenv('db_host')
db_port = os.getenv('db_port')
db_name = os.getenv('db_name')

In [4]:
# to_sql
db_conn = create_engine(f'mysql+pymysql://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}')

In [5]:
# executemany
conn = db_conn.raw_connection()
cursor = conn.cursor()

In [87]:
#when rollback needed
try:
    with db_conn.connect() as conn:
        conn.rollback()
        print("succeed")
except Exception as e:
    print(e)

succeed

# **Carlow**

In [7]:
file_path = '../data/raw/rainfall_Carlow_daily.csv'
file_path2 = '../data/raw/2026-01rainfall_Carlow_daily.csv'
file_path3 = '../data/raw/2026-02rainfall_Carlow_daily.csv'

In [8]:
df = pd.read_csv(file_path, skiprows=24)
df2026 = pd.read_csv(file_path2, skiprows=24)
df2026_02 = pd.read_csv(file_path3, skiprows=24)

In [9]:
df['date'] = pd.to_datetime(df['date'])
df2026['date'] = pd.to_datetime(df2026['date'])
df2026_02['date']=pd.to_datetime(df2026_02['date'])

C:\Users\josr4\AppData\Local\Temp\ipykernel_920\1261846513.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['date'] = pd.to_datetime(df['date'])
C:\Users\josr4\AppData\Local\Temp\ipykernel_920\1261846513.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df2026['date'] = pd.to_datetime(df2026['date'])
C:\Users\josr4\AppData\Local\Temp\ipykernel_920\1261846513.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df2026_02['date']=pd.to_datetime(df2026_02['date'])

### **Data Extraction (2020-2026 Feb)**

In [10]:
start_date = '2020-01-01'
end_date = '2025-12-31'

In [11]:
carlow_rain_recent = (df['date'] >= start_date) & (df['date'] <= end_date)

In [12]:
carlow_filtered = df.loc[carlow_rain_recent]

In [13]:
carlow_filtered = carlow_filtered[['date', 'rain', 'smd_wd', 'smd_md', 'smd_pd', 'maxtp', 'mintp', 'gmin', 'soil', 'glorad', 'cbl', 'pe', 'evap', 'wdsp', 'hm', 'ddhm', 'hg', 'ind']]
carlow_filtered_2026 = df2026[['date', 'rain', 'smd_wd', 'smd_md', 'smd_pd', 'maxtp', 'mintp', 'gmin', 'soil', 'glorad', 'cbl', 'pe', 'evap', 'wdsp', 'hm', 'ddhm', 'hg', 'ind']]
carlow_filtered_2026_02 = df2026_02[['date', 'rain', 'smd_wd', 'smd_md', 'smd_pd', 'maxtp', 'mintp', 'gmin', 'soil', 'glorad', 'cbl', 'pe', 'evap', 'wdsp', 'hm', 'ddhm', 'hg', 'ind']]

In [14]:
carlow_filtered['location'] = 'Carlow'
carlow_filtered_2026['location'] = 'Carlow'
carlow_filtered_2026_02['location']= 'Carlow'

In [15]:
cols = ['location'] + [c for c in carlow_filtered.columns if c != 'location']
cols2 = ['location'] + [c for c in carlow_filtered_2026.columns if c != 'location']
cols3 = ['location'] + [c for c in carlow_filtered_2026_02.columns if c != 'location']
carlow_filtered = carlow_filtered[cols]
carlow_filtered_2026 = carlow_filtered_2026[cols2]
carlow_filtered_2026_02 = carlow_filtered_2026_02[cols3]

### **Checking Missing Data**

In [16]:
print(carlow_filtered.isnull().sum())

location    0
date        0
rain        0
smd_wd      0
smd_md      0
smd_pd      0
maxtp       0
mintp       0
gmin        0
soil        0
glorad      0
cbl         0
pe          0
evap        0
wdsp        0
hm          0
ddhm        0
hg          0
ind         0
dtype: int64

In [17]:
print(carlow_filtered_2026.isnull().sum())

location    0
date        0
rain        0
smd_wd      0
smd_md      0
smd_pd      0
maxtp       0
mintp       0
gmin        0
soil        0
glorad      0
cbl         0
pe          0
evap        0
wdsp        0
hm          0
ddhm        0
hg          0
ind         0
dtype: int64

In [18]:
print(carlow_filtered_2026_02.isnull().sum())

location    0
date        0
rain        0
smd_wd      0
smd_md      0
smd_pd      0
maxtp       0
mintp       0
gmin        0
soil        0
glorad      0
cbl         0
pe          0
evap        0
wdsp        0
hm          0
ddhm        0
hg          0
ind         0
dtype: int64

### **Store Data to db**

In [19]:
try:
    # carlow_filtered.to_sql('obs_hist', con=db_conn, if_exists='append', index=False)
    # carlow_filtered_2026.to_sql('obs_hist', con=db_conn, if_exists='append', index=False)
    carlow_filtered_2026_02.to_sql('obs_hist', con=db_conn, if_exists='append', index=False)
    print("succeed")
except Exception as e:
    print(f"error: {e}")

error: Execution failed on sql 'INSERT INTO obs_hist (location, date, rain, smd_wd, smd_md, smd_pd, maxtp, mintp, gmin, soil, glorad, cbl, pe, evap, wdsp, hm, ddhm, hg, ind) VALUES (:location, :date, :rain, :smd_wd, :smd_md, :smd_pd, :maxtp, :mintp, :gmin, :soil, :glorad, :cbl, :pe, :evap, :wdsp, :hm, :ddhm, :hg, :ind)': (pymysql.err.IntegrityError) (1062, "Duplicate entry 'Carlow-2026-02-01' for key 'obs_hist.PRIMARY'")
[SQL: INSERT INTO obs_hist (location, date, rain, smd_wd, smd_md, smd_pd, maxtp, mintp, gmin, soil, glorad, cbl, pe, evap, wdsp, hm, ddhm, hg, ind) VALUES (%(location)s, %(date)s, %(rain)s, %(smd_wd)s, %(smd_md)s, %(smd_pd)s, %(maxtp)s, %(mintp)s, %(gmin)s, %(soil)s, %(glorad)s, %(cbl)s, %(pe)s, %(evap)s, %(wdsp)s, %(hm)s, %(ddhm)s, %(hg)s, %(ind)s)]
[parameters: [{'location': 'Carlow', 'date': datetime.datetime(2026, 2, 1, 0, 0), 'rain': 1.9, 'smd_wd': 0.0, 'smd_md': -1.6, 'smd_pd': -10.0, 'maxtp': 9.0, 'mintp': -1.5, 'gmin': -0.6, 'soil': 6.144, 'glorad': 445, 'cbl': 992.2, 'pe': 0.3, 'evap': 0.4, 'wdsp': 4.5, 'hm': 13, 'ddhm': 250, 'hg': 21, 'ind': 0}, {'location': 'Carlow', 'date': datetime.datetime(2026, 2, 2, 0, 0), 'rain': 0.0, 'smd_wd': 0.5, 'smd_md': 0.5, 'smd_pd': -9.0, 'maxtp': 8.0, 'mintp': -2.3, 'gmin': -5.4, 'soil': 4.244, 'glorad': 105, 'cbl': 987.6, 'pe': 0.5, 'evap': 0.7, 'wdsp': 6.9, 'hm': 13, 'ddhm': 80, 'hg': 25, 'ind': 0}, {'location': 'Carlow', 'date': datetime.datetime(2026, 2, 3, 0, 0), 'rain': 1.3, 'smd_wd': 0.0, 'smd_md': -0.1, 'smd_pd': -9.1, 'maxtp': 7.6, 'mintp': 5.4, 'gmin': 4.9, 'soil': 5.562, 'glorad': 96, 'cbl': 981.2, 'pe': 0.7, 'evap': 0.9, 'wdsp': 9.8, 'hm': 14, 'ddhm': 60, 'hg': 22, 'ind': 0}, {'location': 'Carlow', 'date': datetime.datetime(2026, 2, 4, 0, 0), 'rain': 1.1, 'smd_wd': 0.0, 'smd_md': -0.5, 'smd_pd': -9.2, 'maxtp': 8.8, 'mintp': 6.4, 'gmin': 5.0, 'soil': 6.364, 'glorad': 226, 'cbl': 978.3, 'pe': 0.6, 'evap': 0.8, 'wdsp': 8.2, 'hm': 12, 'ddhm': 90, 'hg': 20, 'ind': 0}, {'location': 'Carlow', 'date': datetime.datetime(2026, 2, 5, 0, 0), 'rain': 6.1, 'smd_wd': 0.0, 'smd_md': -5.4, 'smd_pd': -10.0, 'maxtp': 7.9, 'mintp': 5.9, 'gmin': 4.0, 'soil': 6.083, 'glorad': 194, 'cbl': 973.0, 'pe': 0.7, 'evap': 1.0, 'wdsp': 11.4, 'hm': 18, 'ddhm': 80, 'hg': 31, 'ind': 0}, {'location': 'Carlow', 'date': datetime.datetime(2026, 2, 6, 0, 0), 'rain': 3.8, 'smd_wd': 0.0, 'smd_md': -3.3, 'smd_pd': -10.0, 'maxtp': 8.7, 'mintp': 6.1, 'gmin': 4.7, 'soil': 6.585, 'glorad': 222, 'cbl': 975.5, 'pe': 0.5, 'evap': 0.7, 'wdsp': 6.0, 'hm': 10, 'ddhm': 80, 'hg': 17, 'ind': 0}, {'location': 'Carlow', 'date': datetime.datetime(2026, 2, 7, 0, 0), 'rain': 1.3, 'smd_wd': 0.0, 'smd_md': -0.9, 'smd_pd': -10.0, 'maxtp': 9.6, 'mintp': 4.6, 'gmin': 4.0, 'soil': 7.056, 'glorad': 308, 'cbl': 983.7, 'pe': 0.4, 'evap': 0.5, 'wdsp': 3.0, 'hm': 7, 'ddhm': 340, 'hg': 11, 'ind': 0}, {'location': 'Carlow', 'date': datetime.datetime(2026, 2, 8, 0, 0), 'rain': 1.8, 'smd_wd': 0.0, 'smd_md': -1.4, 'smd_pd': -10.0, 'maxtp': 11.2, 'mintp': 3.9, 'gmin': -0.0, 'soil': 6.928, 'glorad': 504, 'cbl': 990.2, 'pe': 0.4, 'evap': 0.6, 'wdsp': 3.5, 'hm': 10, 'ddhm': 170, 'hg': 14, 'ind': 0}  ... displaying 10 of 28 total bound parameter sets ...  {'location': 'Carlow', 'date': datetime.datetime(2026, 2, 27, 0, 0), 'rain': 0.0, 'smd_wd': 0.8, 'smd_md': 0.8, 'smd_pd': -8.7, 'maxtp': 11.0, 'mintp': 3.4, 'gmin': 6.1, 'soil': 9.233, 'glorad': 760, 'cbl': 1003.7, 'pe': 0.8, 'evap': 1.1, 'wdsp': 4.8, 'hm': 12, 'ddhm': 340, 'hg': 19, 'ind': 0}, {'location': 'Carlow', 'date': datetime.datetime(2026, 2, 28, 0, 0), 'rain': 0.4, 'smd_wd': 1.1, 'smd_md': 1.1, 'smd_pd': -8.0, 'maxtp': 9.4, 'mintp': 0.1, 'gmin': -3.0, 'soil': 7.162, 'glorad': 850, 'cbl': 1006.9, 'pe': 0.7, 'evap': 1.1, 'wdsp': 6.7, 'hm': 15, 'ddhm': 180, 'hg': 21, 'ind': 0}]]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

### **Data Extraction (2026 Mar)**

#### daily data from Met Éireann

In [ ]:
import requests
from bs4 import BeautifulSoup
from io import StringIO

url = "https://www.met.ie/climate/available-data/daily-data"

session = requests.Session()

r = session.get(url)
r.raise_for_status()

soup = BeautifulSoup(r.text, "html.parser")
token = soup.find("meta", {"name": "token"})["content"]

payload = {
    "stationname": "Oak Park",
    "reportdate": "30/03/2026",
    "_token": token,
}

headers = {
    "Referer": url,
    "Origin": "https://www.met.ie",
    "User-Agent": "Mozilla/5.0",
}

resp = session.post(url, data=payload, headers=headers)
resp.raise_for_status()

tables = pd.read_html(StringIO(resp.text))
print(len(tables))

for i, table in enumerate(tables):
    print(f"\n--- table {i} ---")
    print(table.head())

1

--- table 0 ---
         Date  Rainfall  (mm)  Max Temp  (°C)  Min Temp  (°C)  \
0  29/03/2026             0.8            14.1             4.3

   Grass Min Temp  (°C)  Mean Wind Speed  (knots)  Max Gust  (>= 34 knots)  \
0                   1.8                      11.9                      NaN

   Sunshine  (hours)
0                NaN

In [89]:
if len(tables) > 0:
    df_raw = tables[0]
    raw_rain = df_raw['Rainfall  (mm)'].iloc[0]
    clean_rain = 0.0 if str(raw_rain).strip().lower() == 'tr' else raw_rain
    raw_gmin = None if str(raw_rain).strip().lower() == 'n/a' else raw_rain
    
    march_table = pd.DataFrame({
        'location': ['Oak Park'],
        'date': [pd.to_datetime(df_raw['Date'].iloc[0], dayfirst=True)],
        'rain': [float(clean_rain)],
        'maxtp': [float(df_raw['Max Temp  (°C)'].iloc[0])],
        'mintp': [float(df_raw['Min Temp  (°C)'].iloc[0])],
        'gmin': [float(df_raw['Grass Min Temp  (°C)'].iloc[0])],
        'wdsp': [float(df_raw['Mean Wind Speed  (knots)'].iloc[0])],
        'hg': [float(df_raw['Max Gust  (>= 34 knots)'].iloc[0])]
    })

    try:
        march_table.to_sql('obs_hist', con=db_conn, if_exists='append', index=False)
        print("succeed")
    except Exception as e:
        print(f"error: {e}")

succeed

#### yesterday data from Met Éireann

In [90]:
csv_url = "https://www.met.ie/latest-reports/observations/yesterday/download" 

df = pd.read_csv(csv_url)
oak_park_yesterday = df[df['Station'] == 'Oak Park']

rain = oak_park_yesterday['Rain (mm)'].iloc[0]
maxtp= oak_park_yesterday['Max Temperature (ºC)'].iloc[0]
mintp = oak_park_yesterday['Min Temperature (ºC)'].iloc[0]
wdsp = oak_park_yesterday['Wind Speed (Kts)'].iloc[0]
soil = oak_park_yesterday['Soil (ºC)'].iloc[0]
soil = None if str(soil).strip().lower() == 'nan' else soil
global_rad = oak_park_yesterday['Global (J/cm^2)'].iloc[0]
gmin = oak_park_yesterday['Gmin (ºC)'].iloc[0]

print(rain, maxtp, mintp, wdsp, soil, global_rad, gmin)

0.8 14.1 4.3 11.9 8.4 880 1.8

In [ ]:
with db_conn.connect() as conn:
    query = text("""
        update obs_hist 
        set soil = :soil_val, glorad = :grad
        where date = :target_date
    """)
    
    conn.execute(query, {
        "soil_val": soil,
        "grad": global_rad,
        "target_date": "2026-03-30",
    })
    conn.commit() 

print("succeed")

succeed

### Bias correction

In [24]:
query = """
select date, glorad from obs_hist where date between '2026-02-01' and '2026-02-28'
order by date
"""

obs_feb_df = pd.read_sql(query, db_conn)
obs_feb_df['date'] = pd.to_datetime(obs_feb_df['date']).dt.date
obs_feb_df

          date  glorad
0   2026-02-01   445.0
1   2026-02-02   105.0
2   2026-02-03    96.0
3   2026-02-04   226.0
4   2026-02-05   194.0
5   2026-02-06   222.0
6   2026-02-07   308.0
7   2026-02-08   504.0
8   2026-02-09   267.0
9   2026-02-10   236.0
10  2026-02-11   323.0
11  2026-02-12   315.0
12  2026-02-13   445.0
13  2026-02-14   357.0
14  2026-02-15   631.0
15  2026-02-16   627.0
16  2026-02-17   377.0
17  2026-02-18   179.0
18  2026-02-19   523.0
19  2026-02-20   564.0
20  2026-02-21   252.0
21  2026-02-22   723.0
22  2026-02-23   255.0
23  2026-02-24   236.0
24  2026-02-25   333.0
25  2026-02-26   271.0
26  2026-02-27   760.0
27  2026-02-28   850.0

In [25]:
lat, lon = 52.861, -6.915 # Oak Park station
start_date = "20260201"
end_date = "20260310"

# NASA API 
url = f"https://power.larc.nasa.gov/api/temporal/daily/point?parameters=ALLSKY_SFC_SW_DWN&community=AG&longitude={lon}&latitude={lat}&start={start_date}&end={end_date}&format=JSON"

response = requests.get(url).json()

nasa_data = response['properties']['parameter']['ALLSKY_SFC_SW_DWN']

nasa_list = [{"date": pd.to_datetime(d).date(), "nasa_j_cm2": v*100} for d, v in nasa_data.items()]
nasa_df = pd.DataFrame(nasa_list)

comparison_df = pd.merge(obs_feb_df, nasa_df, on='date')
comparison_df['ratio'] = comparison_df['glorad'] / comparison_df['nasa_j_cm2']

comparison_df

          date  glorad  nasa_j_cm2     ratio
0   2026-02-01   445.0       550.0  0.809091
1   2026-02-02   105.0       194.0  0.541237
2   2026-02-03    96.0       159.0  0.603774
3   2026-02-04   226.0       355.0  0.636620
4   2026-02-05   194.0       203.0  0.955665
5   2026-02-06   222.0       257.0  0.863813
6   2026-02-07   308.0       421.0  0.731591
7   2026-02-08   504.0       548.0  0.919708
8   2026-02-09   267.0       344.0  0.776163
9   2026-02-10   236.0       311.0  0.758842
10  2026-02-11   323.0       411.0  0.785888
11  2026-02-12   315.0       529.0  0.595463
12  2026-02-13   445.0       442.0  1.006787
13  2026-02-14   357.0       282.0  1.265957
14  2026-02-15   631.0       562.0  1.122776
15  2026-02-16   627.0       708.0  0.885593
16  2026-02-17   377.0       331.0  1.138973
17  2026-02-18   179.0       161.0  1.111801
18  2026-02-19   523.0       547.0  0.956124
19  2026-02-20   564.0       581.0  0.970740
20  2026-02-21   252.0       215.0  1.172093
21  2026-02-22   723.0       581.0  1.244406
22  2026-02-23   255.0       352.0  0.724432
23  2026-02-24   236.0       308.0  0.766234
24  2026-02-25   333.0       429.0  0.776224
25  2026-02-26   271.0       313.0  0.865815
26  2026-02-27   760.0       738.0  1.029810
27  2026-02-28   850.0       755.0  1.125828

In [26]:
factor_nasa = comparison_df['ratio'].median()

march_gap = nasa_df[(nasa_df['date'] >= pd.to_datetime("2026-03-01").date())&( nasa_df['date'] <= pd.to_datetime("2026-03-10").date())].copy()
march_gap['final_grad'] = march_gap['nasa_j_cm2'] * factor_nasa

for _, row in march_gap.iterrows():
    print(f"date: {row['date']} | final_rad: {row['final_grad']:.2f} J/cm^2")

date: 2026-03-01 | final_rad: 270.59 J/cm^2
date: 2026-03-02 | final_rad: 788.13 J/cm^2
date: 2026-03-03 | final_rad: 963.27 J/cm^2
date: 2026-03-04 | final_rad: 430.85 J/cm^2
date: 2026-03-05 | final_rad: 141.86 J/cm^2
date: 2026-03-06 | final_rad: 1075.36 J/cm^2
date: 2026-03-07 | final_rad: 777.63 J/cm^2
date: 2026-03-08 | final_rad: 847.68 J/cm^2
date: 2026-03-09 | final_rad: 704.94 J/cm^2
date: 2026-03-10 | final_rad: 606.86 J/cm^2

### Radiation Data Correction (MAR 8-13):
Combined NASA bias-corrected data(8th-10th) and Met Éireann forecast data (11th–13th) were scaled to meet the target total of 4,151 J/cm^2

In [27]:
nasa_data = {
    "2026-03-08": 847.68,
    "2026-03-09": 704.94,
    "2026-03-10": 606.86
}

met_data = {
    "2026-03-11": 315.324 * 3, # Calculated the daily total by applying a weight of 3 to the 3-hour interval data
    "2026-03-12": 105.66 * 6, # a weight of 6 to the 6-hour interval data
    "2026-03-13": 163.296 * 6
}

target = 4151
current_sum = sum(nasa_data.values()) + sum(met_data.values())
scale = target / current_sum

final = {}
for d, v in {**nasa_data, **met_data}.items():
    final[d] = round(v * scale, 2)

for d in sorted(final.keys()):
    print(final[d])

745.62
620.07
533.79
832.08
557.63
861.81

In [28]:
data_to_db = []
for _, row in march_gap[march_gap['date'] <= pd.to_datetime("2026-03-07").date()].iterrows():
    data_to_db.append({
        "glorad": round(row['final_grad'], 2),
        "date": row['date'].strftime('%Y-%m-%d')
    })

for d in sorted(final.keys()):
    data_to_db.append({
        "glorad": final[d], 
        "date": d
    })


with db_conn.connect() as conn:
    query = text("update obs_hist set glorad = :glorad where date = :date")
    result = conn.execute(query, data_to_db)

    conn.commit()

    print("succeed")

succeed

## **Fetching Data via API**

## **1.   Environmental Parameters**

### **1.1   Checking River Codes near Carlow**

In [29]:
endp = "https://wfdapi.edenireland.ie/api/charts/catchments"

In [30]:
r = requests.get(endp, timeout = 30)
r.raise_for_status() # HTTP success or exception

In [31]:
data = r.json()
data

{'Success': True,
 'Count': 46,
 'Model': [{'Name': 'Foyle', 'Code': '01', 'Id': 1},
  {'Name': 'Lough Neagh & Lower Bann', 'Code': '03', 'Id': 2},
  {'Name': 'Newry, Fane, Glyde and Dee', 'Code': '06', 'Id': 3},
  {'Name': 'Boyne', 'Code': '07', 'Id': 4},
  {'Name': 'Nanny-Delvin', 'Code': '08', 'Id': 5},
  {'Name': 'Liffey and Dublin Bay', 'Code': '09', 'Id': 6},
  {'Name': 'Ovoca-Vartry', 'Code': '10', 'Id': 7},
  {'Name': 'Owenavorragh', 'Code': '11', 'Id': 8},
  {'Name': 'Slaney & Wexford Harbour', 'Code': '12', 'Id': 9},
  {'Name': 'Ballyteigue-Bannow', 'Code': '13', 'Id': 10},
  {'Name': 'Barrow', 'Code': '14', 'Id': 11},
  {'Name': 'Nore', 'Code': '15', 'Id': 12},
  {'Name': 'Suir', 'Code': '16', 'Id': 13},
  {'Name': 'Colligan-Mahon', 'Code': '17', 'Id': 14},
  {'Name': 'Blackwater (Munster)', 'Code': '18', 'Id': 15},
  {'Name': 'Lee, Cork Harbour and Youghal Bay', 'Code': '19', 'Id': 16},
  {'Name': 'Bandon-Ilen', 'Code': '20', 'Id': 17},
  {'Name': 'Dunmanus-Bantry-Kenmare', 'Code': '21', 'Id': 18},
  {'Name': 'Laune-Maine-Dingle Bay', 'Code': '22', 'Id': 19},
  {'Name': 'Tralee Bay-Feale', 'Code': '23', 'Id': 20},
  {'Name': 'Shannon Estuary South', 'Code': '24', 'Id': 21},
  {'Name': 'Lower Shannon', 'Code': '25A', 'Id': 22},
  {'Name': 'Lower Shannon', 'Code': '25B', 'Id': 23},
  {'Name': 'Lower Shannon', 'Code': '25C', 'Id': 24},
  {'Name': 'Lower Shannon', 'Code': '25D', 'Id': 25},
  {'Name': 'Upper Shannon', 'Code': '26A', 'Id': 26},
  {'Name': 'Upper Shannon', 'Code': '26B', 'Id': 27},
  {'Name': 'Upper Shannon', 'Code': '26C', 'Id': 28},
  {'Name': 'Upper Shannon', 'Code': '26D', 'Id': 29},
  {'Name': 'Upper Shannon', 'Code': '26E', 'Id': 30},
  {'Name': 'Upper Shannon', 'Code': '26F', 'Id': 31},
  {'Name': 'Upper Shannon', 'Code': '26G', 'Id': 32},
  {'Name': 'Shannon Estuary North', 'Code': '27', 'Id': 33},
  {'Name': 'Mal Bay', 'Code': '28', 'Id': 34},
  {'Name': 'Galway Bay South East', 'Code': '29', 'Id': 35},
  {'Name': 'Corrib', 'Code': '30', 'Id': 36},
  {'Name': 'Galway Bay North', 'Code': '31', 'Id': 37},
  {'Name': 'Erriff-Clew Bay', 'Code': '32', 'Id': 38},
  {'Name': 'Blacksod-Broadhaven', 'Code': '33', 'Id': 39},
  {'Name': 'Moy & Killala Bay', 'Code': '34', 'Id': 40},
  {'Name': 'Sligo Bay & Drowse', 'Code': '35', 'Id': 41},
  {'Name': 'Erne', 'Code': '36', 'Id': 42},
  {'Name': 'Donegal Bay North', 'Code': '37', 'Id': 43},
  {'Name': 'Gweebarra-Sheephaven', 'Code': '38', 'Id': 44},
  {'Name': 'Lough Swilly', 'Code': '39', 'Id': 45},
  {'Name': 'Donagh-Moville', 'Code': '40', 'Id': 46}],
 'Type': 0}

*   **count: 46 catchments**

In [32]:
type(data)

dict

In [33]:
data.keys()

dict_keys(['Success', 'Count', 'Model', 'Type'])

Barrow / Nore / Suir: key catchments in South-East

In [34]:
target = ["Barrow", "Nore", "Suir"]

In [35]:
filtered_target = [item for item in data['Model'] if item['Name'] in target]

In [36]:
filtered_target # Barrow's code: 14

[{'Name': 'Barrow', 'Code': '14', 'Id': 11},
 {'Name': 'Nore', 'Code': '15', 'Id': 12},
 {'Name': 'Suir', 'Code': '16', 'Id': 13}]

*   **Barrow's code: 14**

### **1.2   Barrow's Subcatchment**

In [37]:
endp2 = "https://wfdapi.edenireland.ie/api/catchment/14"

In [38]:
r2 = requests.get(endp2, timeout = 30)
r2.raise_for_status()

In [39]:
data2 = r2.json()
data2

{'Code': '14',
 'Name': 'Barrow',
 'Profile': 'This catchment includes the area drained by the River Barrow upstream of the River Nore confluence and all streams entering tidal water between the Barrow railway bridge at Great Island and Ringwood, Co. Kilkenny, draining a total area of 3,025km². The largest urban centre in the catchment is Carlow. The other main urban centres in this catchment are New Ross, Graiguenamanagh, Athy, Portlaoise, Mountmellick, Portarlington, Monasterevin and Kildare. The total population of the catchment is approximately 188117 with a population density of 62 people per km². The Barrow catchment is underlain in its flat northern area by limestones of varying purity which continue down the western side of the catchment and sustain good groundwater resources in places. On the eastern side of the catchment, granites dominate, culminating in the summits of the Blackstairs Mountains.',
 'Area': 3015.7,
 'GeometryExtent': '230320,114147,289600,234340',
 'LastCycleApproved': 'WFD Cycle 3',
 'Subcatchments': [{'Name': 'Barrow_SC_090',
   'Code': '14_13',
   'Area': 189.01,
   'GeometryExtent': '270560,154000,285000,184875'},
  {'Name': 'Barrow_SC_100',
   'Code': '14_4',
   'Area': 100.43,
   'GeometryExtent': '268338,150386,276220,174660'},
  {'Name': 'Barrow_SC_140',
   'Code': '14_10',
   'Area': 152.67,
   'GeometryExtent': '270657,141700,284280,161060'},
  {'Name': 'Barrow_SC_110',
   'Code': '14_5',
   'Area': 100.5,
   'GeometryExtent': '262360,161780,270725,183580'},
  {'Name': 'Slate_SC_010',
   'Code': '14_16',
   'Area': 215.46,
   'GeometryExtent': '261260,210460,284300,230938'},
  {'Name': 'Lerr_SC_010',
   'Code': '14_6',
   'Area': 111.07,
   'GeometryExtent': '271680,176320,286540,192020'},
  {'Name': 'Greese_SC_010',
   'Code': '14_9',
   'Area': 144.25,
   'GeometryExtent': '271720,182500,289600,203900'},
  {'Name': 'Figile_SC_010',
   'Code': '14_3',
   'Area': 95.22,
   'GeometryExtent': '258720,221860,276197,233996'},
  {'Name': 'Barrow_SC_080',
   'Code': '14_2',
   'Area': 83.85,
   'GeometryExtent': '265840,184640,278120,199760'},
  {'Name': 'Barrow_SC_060',
   'Code': '14_18',
   'Area': 273.36,
   'GeometryExtent': '261274,196855,286920,215620'},
  {'Name': 'Barrow_SC_120',
   'Code': '14_8',
   'Area': 123.11,
   'GeometryExtent': '257740,150380,270690,164940'},
  {'Name': 'Barrow_SC_130',
   'Code': '14_7',
   'Area': 111.93,
   'GeometryExtent': '261920,130374,273820,153647'},
  {'Name': 'Barrow_SC_050',
   'Code': '14_17',
   'Area': 241.2,
   'GeometryExtent': '249820,185680,265947,212417'},
  {'Name': 'Barrow_SC_020',
   'Code': '14_11',
   'Area': 154.56,
   'GeometryExtent': '243960,189280,258270,212861'},
  {'Name': 'Barrow_SC_070',
   'Code': '14_12',
   'Area': 160.83,
   'GeometryExtent': '257880,174109,272007,196855'},
  {'Name': 'Barrow_SC_010',
   'Code': '14_15',
   'Area': 206.45,
   'GeometryExtent': '230320,196920,246470,217660'},
  {'Name': 'Figile_SC_020',
   'Code': '14_14',
   'Area': 206.33,
   'GeometryExtent': '241720,217820,265380,234340'},
  {'Name': 'Barrow_SC_030',
   'Code': '14_1',
   'Area': 58.05,
   'GeometryExtent': '241500,209276,258285,217280'},
  {'Name': 'Barrow_SC_040',
   'Code': '14_20',
   'Area': 129.76,
   'GeometryExtent': '240220,210620,266740,223060'},
  {'Name': 'Barrow_SC_150',
   'Code': '14_19',
   'Area': 157.56,
   'GeometryExtent': '267222,114147,281980,144340'}]}

*   The largest urban catchment in Barrow is Carlow
*   Barrow_SC_060 has the largest area

### **1.3   Water Bodies within Carlow (Barrow Catchment)**

In [40]:
endp3 = "https://wfdapi.edenireland.ie/api/search?v=barrow&size=100"

In [41]:
r3 = requests.get(endp3, timeout = 30)
r3.raise_for_status()

In [42]:
data3 = r3.json()
data3

{'Results': [{'Name': 'Barrow',
   'Type': 'Catchment',
   'Organisation': 'Kildare County Council',
   'Code': '14',
   'GeometryExtent': '230320,114147,289600,234340'},
  {'Name': 'Barrow_SC_030',
   'Type': 'Subcatchment',
   'Organisation': 'Offaly County Council',
   'Code': '14_1',
   'GeometryExtent': '241500,209276,258285,217280'},
  {'Name': 'Barrow_SC_140',
   'Type': 'Subcatchment',
   'Organisation': 'Carlow County Council',
   'Code': '14_10',
   'GeometryExtent': '270657,141700,284280,161060'},
  {'Name': 'Barrow_SC_020',
   'Type': 'Subcatchment',
   'Organisation': 'Laois County Council',
   'Code': '14_11',
   'GeometryExtent': '243960,189280,258270,212861'},
  {'Name': 'Barrow_SC_070',
   'Type': 'Subcatchment',
   'Organisation': 'Laois County Council',
   'Code': '14_12',
   'GeometryExtent': '257880,174109,272007,196855'},
  {'Name': 'Barrow_SC_090',
   'Type': 'Subcatchment',
   'Organisation': 'Carlow County Council',
   'Code': '14_13',
   'GeometryExtent': '270560,154000,285000,184875'},
  {'Name': 'Barrow_SC_010',
   'Type': 'Subcatchment',
   'Organisation': 'Laois County Council',
   'Code': '14_15',
   'GeometryExtent': '230320,196920,246470,217660'},
  {'Name': 'Barrow_SC_050',
   'Type': 'Subcatchment',
   'Organisation': 'Laois County Council',
   'Code': '14_17',
   'GeometryExtent': '249820,185680,265947,212417'},
  {'Name': 'Barrow_SC_060',
   'Type': 'Subcatchment',
   'Organisation': 'Kildare County Council',
   'Code': '14_18',
   'GeometryExtent': '261274,196855,286920,215620'},
  {'Name': 'Barrow_SC_150',
   'Type': 'Subcatchment',
   'Organisation': 'Wexford County Council',
   'Code': '14_19',
   'GeometryExtent': '267222,114147,281980,144340'},
  {'Name': 'Barrow_SC_080',
   'Type': 'Subcatchment',
   'Organisation': 'Kildare County Council',
   'Code': '14_2',
   'GeometryExtent': '265840,184640,278120,199760'},
  {'Name': 'Barrow_SC_040',
   'Type': 'Subcatchment',
   'Organisation': 'Offaly County Council',
   'Code': '14_20',
   'GeometryExtent': '240220,210620,266740,223060'},
  {'Name': 'Barrow_SC_100',
   'Type': 'Subcatchment',
   'Organisation': 'Carlow County Council',
   'Code': '14_4',
   'GeometryExtent': '268338,150386,276220,174660'},
  {'Name': 'Barrow_SC_110',
   'Type': 'Subcatchment',
   'Organisation': 'Carlow County Council',
   'Code': '14_5',
   'GeometryExtent': '262360,161780,270725,183580'},
  {'Name': 'Barrow_SC_130',
   'Type': 'Subcatchment',
   'Organisation': 'Kilkenny County Council',
   'Code': '14_7',
   'GeometryExtent': '261920,130374,273820,153647'},
  {'Name': 'Barrow_SC_120',
   'Type': 'Subcatchment',
   'Organisation': 'Kilkenny County Council',
   'Code': '14_8',
   'GeometryExtent': '257740,150380,270690,164940'},
  {'Name': 'Grand Canal Barrow Line (Barrow)',
   'Type': 'River',
   'Organisation': 'Kildare County Council',
   'Code': 'IE_14_AWB_GCBL',
   'GeometryExtent': '260682,193458,277922,225588'},
  {'Name': 'Grand Canal Milltown Feeder (Barrow)',
   'Type': 'River',
   'Organisation': 'Kildare County Council',
   'Code': 'IE_14_AWB_GCMF',
   'GeometryExtent': '274769,215500,277237,224447'},
  {'Name': 'Grand Canal Main Line East (Barrow)',
   'Type': 'River',
   'Organisation': 'Kildare County Council',
   'Code': 'IE_14_AWB_GCMLE',
   'GeometryExtent': '268758,224968,281956,230683'},
  {'Name': 'Grand Canal Main Line West (Barrow)',
   'Type': 'River',
   'Organisation': 'Kildare County Council',
   'Code': 'IE_14_AWB_GCMLW',
   'GeometryExtent': '244171,227220,254820,232047'},
  {'Name': 'Barrow Suir Nore Estuary',
   'Type': 'Transitional',
   'Organisation': 'Wexford County Council',
   'Code': 'IE_SE_100_0100',
   'GeometryExtent': '268422,103288,275096,115982'},
  {'Name': 'Barrow Nore Estuary Upper',
   'Type': 'Transitional',
   'Organisation': 'Wexford County Council',
   'Code': 'IE_SE_100_0250',
   'GeometryExtent': '270604,127364,272238,130565'},
  {'Name': 'Upper Barrow Estuary',
   'Type': 'Transitional',
   'Organisation': 'Kilkenny County Council',
   'Code': 'IE_SE_100_0300',
   'GeometryExtent': '270718,130299,273943,139475'},
  {'Name': 'BARROW_010',
   'Type': 'River',
   'Organisation': 'Laois County Council',
   'Code': 'IE_SE_14B010060',
   'GeometryExtent': '231121,204428,237216,211039'},
  {'Name': 'BARROW_020',
   'Type': 'River',
   'Organisation': 'Laois County Council',
   'Code': 'IE_SE_14B010200',
   'GeometryExtent': '234472,210790,238685,215113'},
  {'Name': 'BARROW_030',
   'Type': 'River',
   'Organisation': 'Laois County Council',
   'Code': 'IE_SE_14B010300',
   'GeometryExtent': '237648,208307,243395,215546'},
  {'Name': 'BARROW_040',
   'Type': 'River',
   'Organisation': 'Laois County Council',
   'Code': 'IE_SE_14B010500',
   'GeometryExtent': '237880,206025,246470,212318'},
  {'Name': 'BARROW_050',
   'Type': 'River',
   'Organisation': 'Laois County Council',
   'Code': 'IE_SE_14B010550',
   'GeometryExtent': '246264,204594,250369,210087'},
  {'Name': 'BARROW_060',
   'Type': 'River',
   'Organisation': 'Laois County Council',
   'Code': 'IE_SE_14B010700',
   'GeometryExtent': '247748,208181,253684,211641'},
  {'Name': 'BARROW_070',
   'Type': 'River',
   'Organisation': 'Offaly County Council',
   'Code': 'IE_SE_14B010780',
   'GeometryExtent': '250847,210749,254340,212861'},
  {'Name': 'BARROW_080',
   'Type': 'River',
   'Organisation': 'Laois County Council',
   'Code': 'IE_SE_14B010900',
   'GeometryExtent': '254340,212085,258270,212840'},
  {'Name': 'BARROW_090',
   'Type': 'River',
   'Organisation': 'Laois County Council',
   'Code': 'IE_SE_14B011000',
   'GeometryExtent': '258270,210620,262357,212417'},
  {'Name': 'BARROW_100',
   'Type': 'River',
   'Organisation': 'Kildare County Council',
   'Code': 'IE_SE_14B011130',
   'GeometryExtent': '262357,208905,265196,210745'},
  {'Name': 'BARROW_110',
   'Type': 'River',
   'Organisation': 'Laois County Council',
   'Code': 'IE_SE_14B011300',
   'GeometryExtent': '259797,205718,264343,210150'},
  {'Name': 'BARROW_120',
   'Type': 'River',
   'Organisation': 'Kildare County Council',
   'Code': 'IE_SE_14B011500',
   'GeometryExtent': '259229,196855,268155,209088'},
  {'Name': 'BARROW_130',
   'Type': 'River',
   'Organisation': 'Kildare County Council',
   'Code': 'IE_SE_14B011600',
   'GeometryExtent': '265943,192680,268622,196855'},
  {'Name': 'BARROW_140',
   'Type': 'River',
   'Organisation': 'Kildare County Council',
   'Code': 'IE_SE_14B011900',
   'GeometryExtent': '264297,188160,270382,194346'},
  {'Name': 'BARROW_150',
   'Type': 'River',
   'Organisation': 'Kildare County Council',
   'Code': 'IE_SE_14B012000',
   'GeometryExtent': '270351,184696,274687,191896'},
  {'Name': 'BARROW_160',
   'Type': 'River',
   'Organisation': 'Laois County Council',
   'Code': 'IE_SE_14B012460',
   'GeometryExtent': '268267,174109,273289,185580'},
  {'Name': 'BARROW_170',
   'Type': 'River',
   'Organisation': 'Carlow County Council',
   'Code': 'IE_SE_14B012600',
   'GeometryExtent': '266857,170420,271021,177834'},
  {'Name': 'BARROW_180',
   'Type': 'River',
   'Organisation': 'Carlow County Council',
   'Code': 'IE_SE_14B012700',
   'GeometryExtent': '266975,165435,274998,172502'},
  {'Name': 'BARROW_190',
   'Type': 'River',
   'Organisation': 'Carlow County Council',
   'Code': 'IE_SE_14B012820',
   'GeometryExtent': '265791,162300,270725,165435'},
  {'Name': 'BARROW_200',
   'Type': 'River',
   'Organisation': 'Carlow County Council',
   'Code': 'IE_SE_14B012920',
   'GeometryExtent': '268920,161313,274492,163881'},
  {'Name': 'BARROW_210',
   'Type': 'River',
   'Organisation': 'Carlow County Council',
   'Code': 'IE_SE_14B013100',
   'GeometryExtent': '265480,153255,272890,161421'},
  {'Name': 'BARROW_220',
   'Type': 'River',
   'Organisation': 'Carlow County Council',
   'Code': 'IE_SE_14B013300',
   'GeometryExtent': '268475,150146,271424,153647'},
  {'Name': 'BARROW_230',
   'Type': 'River',
   'Organisation': 'Kilkenny County Council',
   'Code': 'IE_SE_14B013514',
   'GeometryExtent': '268755,142136,275221,150386'},
  {'Name': 'BARROW_240',
   'Type': 'River',
   'Organisation': 'Kilkenny County Council',
   'Code': 'IE_SE_14B013600',
   'GeometryExtent': '271023,139313,272477,143378'},
  {'Name': 'Barrowen Emlaghkeeragh',
   'Type': 'Lake',
   'Organisation': 'Galway County Council',
   'Code': 'IE_WE_31_183',
   'GeometryExtent': '65048.5,242197,66567.1,244071'}],
 'Page': 0,
 'Size': 100,
 'Total': 48}

In [43]:
results = [ r for r in data3["Results"] if r["Type"] == "River"and r["Organisation"] == "Carlow County Council"]
results

[{'Name': 'BARROW_170',
  'Type': 'River',
  'Organisation': 'Carlow County Council',
  'Code': 'IE_SE_14B012600',
  'GeometryExtent': '266857,170420,271021,177834'},
 {'Name': 'BARROW_180',
  'Type': 'River',
  'Organisation': 'Carlow County Council',
  'Code': 'IE_SE_14B012700',
  'GeometryExtent': '266975,165435,274998,172502'},
 {'Name': 'BARROW_190',
  'Type': 'River',
  'Organisation': 'Carlow County Council',
  'Code': 'IE_SE_14B012820',
  'GeometryExtent': '265791,162300,270725,165435'},
 {'Name': 'BARROW_200',
  'Type': 'River',
  'Organisation': 'Carlow County Council',
  'Code': 'IE_SE_14B012920',
  'GeometryExtent': '268920,161313,274492,163881'},
 {'Name': 'BARROW_210',
  'Type': 'River',
  'Organisation': 'Carlow County Council',
  'Code': 'IE_SE_14B013100',
  'GeometryExtent': '265480,153255,272890,161421'},
 {'Name': 'BARROW_220',
  'Type': 'River',
  'Organisation': 'Carlow County Council',
  'Code': 'IE_SE_14B013300',
  'GeometryExtent': '268475,150146,271424,153647'}]

In [44]:
len(results)

6

*   **Identified 6 river segments of the Barrow catchment within Carlow**

### **1.4   Identification of Segments for Future Iteration**

In [45]:
endp4 = "https://wfdapi.edenireland.ie/api/waterbody/IE_SE_14B012600"

In [46]:
r4 = requests.get(endp4, timeout = 30)
r4.raise_for_status()

In [47]:
data4 = r4.json()
data4

{'Catchment': [{'Name': 'Barrow', 'Code': '14'}],
 'Subcatchment': [{'Name': 'Barrow_SC_100', 'Code': '14_4'},
  {'Name': 'Barrow_SC_110', 'Code': '14_5'}],
 'Code': 'IE_SE_14B012600',
 'Name': 'BARROW_170',
 'LocalAuthority': 'Carlow County Council',
 'Type': 'River',
 'Rbd': 'South Eastern',
 'Tier1Risk': 'At risk',
 'ProtectedArea': None,
 'ArtificialName': None,
 'ModifiedName': None,
 'Easting': 269004.41,
 'Northing': 174009.61,
 'Latitude': 52.8130078,
 'Longitude': -6.9773591,
 'GeometryExtent': '266857,170420,271021,177834',
 'Status': [{'Code': 'SW 2007-2009',
   'Status': [{'Status': 'Moderate',
     'Name': 'Ecological Status or Potential',
     'Id': '82c44189-7fb3-e411-b3b4-0050568a69e2',
     'ParentId': None,
     'AssessmentTechnique': 'Monitoring',
     'StatusConfidence': 'no information or unknown'},
    {'Status': 'Moderate',
     'Name': 'Biological Status or Potential',
     'Id': '354c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '82c44189-7fb3-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Moderate',
     'Name': 'Invertebrate Status or Potential',
     'Id': '434c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '354c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Supporting Chemistry Conditions',
     'Id': '4b4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '82c44189-7fb3-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'General Conditions',
     'Id': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4b4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Oxygenation Conditions',
     'Id': '554c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Acidification Conditions',
     'Id': '5d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'pH',
     'Id': '5f4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '5d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Nutrient Conditions',
     'Id': '634c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Fail',
     'Name': 'Nitrogen Conditions',
     'Id': '0a226dd5-7310-e711-9f02-0050568a69e2',
     'ParentId': '634c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Fail',
     'Name': 'Nitrate',
     'Id': '674c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '0a226dd5-7310-e711-9f02-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Ammonium',
     'Id': '6b4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '0a226dd5-7310-e711-9f02-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Phosphorous Conditions',
     'Id': 'f07240df-7310-e711-9f02-0050568a69e2',
     'ParentId': '634c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Orthophosphate',
     'Id': '6f4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': 'f07240df-7310-e711-9f02-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''}],
   'Failures': [],
   'HasFailures': False},
  {'Code': 'SW 2010-2012',
   'Status': [{'Status': 'Moderate',
     'Name': 'Ecological Status or Potential',
     'Id': '82c44189-7fb3-e411-b3b4-0050568a69e2',
     'ParentId': None,
     'AssessmentTechnique': 'Monitoring',
     'StatusConfidence': 'no information or unknown'},
    {'Status': 'Moderate',
     'Name': 'Biological Status or Potential',
     'Id': '354c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '82c44189-7fb3-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Moderate',
     'Name': 'Invertebrate Status or Potential',
     'Id': '434c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '354c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Supporting Chemistry Conditions',
     'Id': '4b4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '82c44189-7fb3-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'General Conditions',
     'Id': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4b4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Oxygenation Conditions',
     'Id': '554c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Acidification Conditions',
     'Id': '5d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'pH',
     'Id': '5f4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '5d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Nutrient Conditions',
     'Id': '634c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Moderate',
     'Name': 'Nitrogen Conditions',
     'Id': '0a226dd5-7310-e711-9f02-0050568a69e2',
     'ParentId': '634c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Moderate',
     'Name': 'Nitrate',
     'Id': '674c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '0a226dd5-7310-e711-9f02-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'High',
     'Name': 'Ammonium',
     'Id': '6b4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '0a226dd5-7310-e711-9f02-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'High',
     'Name': 'Phosphorous Conditions',
     'Id': 'f07240df-7310-e711-9f02-0050568a69e2',
     'ParentId': '634c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'High',
     'Name': 'Orthophosphate',
     'Id': '6f4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': 'f07240df-7310-e711-9f02-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''}],
   'Failures': [],
   'HasFailures': False},
  {'Code': 'SW 2010-2015',
   'Status': [{'Status': 'Moderate',
     'Name': 'Ecological Status or Potential',
     'Id': '82c44189-7fb3-e411-b3b4-0050568a69e2',
     'ParentId': None,
     'AssessmentTechnique': 'Monitoring',
     'StatusConfidence': 'high confidence'},
    {'Status': 'Moderate',
     'Name': 'Biological Status or Potential',
     'Id': '354c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '82c44189-7fb3-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Moderate',
     'Name': 'Invertebrate Status or Potential',
     'Id': '434c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '354c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Supporting Chemistry Conditions',
     'Id': '4b4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '82c44189-7fb3-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'General Conditions',
     'Id': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4b4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Oxygenation Conditions',
     'Id': '554c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Dissolved Oxygen (% Sat)',
     'Id': '574c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '554c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'High',
     'Name': 'Other determinand for oxygenation conditions',
     'Id': '5b4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '554c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Acidification Conditions',
     'Id': '5d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'pH',
     'Id': '5f4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '5d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Nutrient Conditions',
     'Id': '634c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Moderate',
     'Name': 'Nitrogen Conditions',
     'Id': '0a226dd5-7310-e711-9f02-0050568a69e2',
     'ParentId': '634c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Moderate',
     'Name': 'Nitrate',
     'Id': '674c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '0a226dd5-7310-e711-9f02-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'High',
     'Name': 'Ammonium',
     'Id': '6b4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '0a226dd5-7310-e711-9f02-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'High',
     'Name': 'Phosphorous Conditions',
     'Id': 'f07240df-7310-e711-9f02-0050568a69e2',
     'ParentId': '634c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'High',
     'Name': 'Orthophosphate',
     'Id': '6f4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': 'f07240df-7310-e711-9f02-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''}],
   'Failures': [],
   'HasFailures': False},
  {'Code': 'SW 2013-2018',
   'Status': [{'Status': 'Moderate',
     'Name': 'Ecological Status or Potential',
     'Id': '82c44189-7fb3-e411-b3b4-0050568a69e2',
     'ParentId': None,
     'AssessmentTechnique': 'Monitoring',
     'StatusConfidence': 'high confidence'},
    {'Status': 'Moderate',
     'Name': 'Biological Status or Potential',
     'Id': '354c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '82c44189-7fb3-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Moderate',
     'Name': 'Invertebrate Status or Potential',
     'Id': '434c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '354c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Supporting Chemistry Conditions',
     'Id': '4b4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '82c44189-7fb3-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'General Conditions',
     'Id': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4b4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Oxygenation Conditions',
     'Id': '554c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Dissolved Oxygen (% Sat)',
     'Id': '574c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '554c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'High',
     'Name': 'Other determinand for oxygenation conditions',
     'Id': '5b4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '554c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Acidification Conditions',
     'Id': '5d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'pH',
     'Id': '5f4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '5d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Nutrient Conditions',
     'Id': '634c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Moderate',
     'Name': 'Nitrogen Conditions',
     'Id': '0a226dd5-7310-e711-9f02-0050568a69e2',
     'ParentId': '634c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Moderate',
     'Name': 'Nitrate',
     'Id': '674c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '0a226dd5-7310-e711-9f02-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'High',
     'Name': 'Ammonium',
     'Id': '6b4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '0a226dd5-7310-e711-9f02-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'High',
     'Name': 'Phosphorous Conditions',
     'Id': 'f07240df-7310-e711-9f02-0050568a69e2',
     'ParentId': '634c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'High',
     'Name': 'Orthophosphate',
     'Id': '6f4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': 'f07240df-7310-e711-9f02-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''}],
   'Failures': [],
   'HasFailures': False},
  {'Code': 'SW 2016-2021',
   'Status': [{'Status': 'Moderate',
     'Name': 'Ecological Status or Potential',
     'Id': '82c44189-7fb3-e411-b3b4-0050568a69e2',
     'ParentId': None,
     'AssessmentTechnique': 'Monitoring',
     'StatusConfidence': 'high confidence'},
    {'Status': 'Moderate',
     'Name': 'Biological Status or Potential',
     'Id': '354c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '82c44189-7fb3-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Moderate',
     'Name': 'Invertebrate Status or Potential',
     'Id': '434c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '354c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Supporting Chemistry Conditions',
     'Id': '4b4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '82c44189-7fb3-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'General Conditions',
     'Id': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4b4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Oxygenation Conditions',
     'Id': '554c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Dissolved Oxygen (% Sat)',
     'Id': '574c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '554c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'High',
     'Name': 'Other determinand for oxygenation conditions',
     'Id': '5b4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '554c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Acidification Conditions',
     'Id': '5d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'pH',
     'Id': '5f4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '5d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Nutrient Conditions',
     'Id': '634c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Moderate',
     'Name': 'Nitrogen Conditions',
     'Id': '0a226dd5-7310-e711-9f02-0050568a69e2',
     'ParentId': '634c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Moderate',
     'Name': 'Nitrate',
     'Id': '674c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '0a226dd5-7310-e711-9f02-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'High',
     'Name': 'Ammonium',
     'Id': '6b4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '0a226dd5-7310-e711-9f02-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'High',
     'Name': 'Phosphorous Conditions',
     'Id': 'f07240df-7310-e711-9f02-0050568a69e2',
     'ParentId': '634c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'High',
     'Name': 'Orthophosphate',
     'Id': '6f4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': 'f07240df-7310-e711-9f02-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''}],
   'Failures': [],
   'HasFailures': False},
  {'Code': 'SW 2019-2024',
   'Status': [{'Status': 'Moderate',
     'Name': 'Ecological Status or Potential',
     'Id': '82c44189-7fb3-e411-b3b4-0050568a69e2',
     'ParentId': None,
     'AssessmentTechnique': 'Monitoring',
     'StatusConfidence': 'medium confidence'},
    {'Status': 'Moderate',
     'Name': 'Biological Status or Potential',
     'Id': '354c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '82c44189-7fb3-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Moderate',
     'Name': 'Invertebrate Status or Potential',
     'Id': '434c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '354c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Supporting Chemistry Conditions',
     'Id': '4b4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '82c44189-7fb3-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'General Conditions',
     'Id': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4b4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Oxygenation Conditions',
     'Id': '554c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',

## **2.   Rainfall Forecast**

In [48]:
lat, lon = 52.841, -6.926
endp5 = f"http://openaccess.pf.api.met.ie/metno-wdb2ts/locationforecast?lat={lat};long={lon}"

r5 = requests.get(endp5)

In [49]:
data5 = xmltodict.parse(r5.text)

In [50]:
print(data5.keys())

dict_keys(['weatherdata'])

In [51]:
print(data5['weatherdata'].keys())

dict_keys(['@xmlns:xsi', '@xsi:noNamespaceSchemaLocation', '@created', 'meta', 'product'])

In [52]:
print(data5['weatherdata']['product'].keys())

dict_keys(['@class', 'time'])

In [53]:
data5['weatherdata']['product']['time'][0]

{'@datatype': 'forecast',
 '@from': '2026-03-25T12:00:00Z',
 '@to': '2026-03-25T12:00:00Z',
 'location': {'@altitude': '58',
  '@latitude': '52.8410',
  '@longitude': '-6.9260',
  'temperature': {'@id': 'TTT', '@unit': 'celsius', '@value': '7.7'},
  'windDirection': {'@id': 'dd', '@deg': '291.2', '@name': 'W'},
  'windSpeed': {'@id': 'ff',
   '@mps': '7.5',
   '@beaufort': '4',
   '@name': 'Moderate breeze'},
  'windGust': {'@id': 'ff_gust', '@mps': '16.8'},
  'globalRadiation': {'@value': '513.1', '@unit': 'W/m^2'},
  'humidity': {'@value': '56.2', '@unit': 'percent'},
  'pressure': {'@id': 'pr', '@unit': 'hPa', '@value': '1017.0'},
  'cloudiness': {'@id': 'NN', '@percent': '61.7'},
  'lowClouds': {'@id': 'LOW', '@percent': '60.2'},
  'mediumClouds': {'@id': 'MEDIUM', '@percent': '9.5'},
  'highClouds': {'@id': 'HIGH', '@percent': '0.0'},
  'dewpointTemperature': {'@id': 'TD', '@unit': 'celsius', '@value': '-0.7'}}}

In [54]:
merged_forecasts = {}

my_map_id = 1

for entry in data5['weatherdata']['product']['time']:
    raw_time = entry['@to']
    time_key = raw_time.replace('T', ' ').replace('Z', '')
    location = entry.get('location', {})

    if time_key not in merged_forecasts:
        merged_forecasts[time_key] = {'forecast_time': time_key, 'location_id': my_map_id}
    
    if 'temperature' in location:
        merged_forecasts[time_key].update({
            'temp': location['temperature'].get('@value'),
            'wind_speed': location['windSpeed'].get("@mps"),
            'wind_gust': location['windGust'].get('@mps'),  
            'wind_dir': location['windDirection'].get('@deg'),   
            'humidity': location['humidity'].get('@value'),
            'pressure': location['pressure'].get('@value'),
            'dew_point': location['dewpointTemperature'].get('@value'), 
            'global_rad': location['globalRadiation'].get('@value')     
        })

    if 'precipitation' in location:
        p_val = location['precipitation'].get('@value')

        if p_val:
            print(f"precip: {p_val}")
            
        merged_forecasts[time_key].update({
            'precip': location['precipitation'].get('@value'),
            'symbol_id': location.get('symbol', {}).get('@id')
        })

# data = []
# for val in merged_forecasts.values():
#     data.append((
#         val['location_id'],
#         val['forecast_time'],
#         val.get('temp'),
#         val.get('precip', 0.0),
#         val.get('humidity'),
#         val.get('wind_speed'),
#         val.get('wind_gust'),
#         val.get('wind_dir'),
#         val.get('dew_point'),
#         val.get('pressure'),
#         val.get('global_rad'),
#         val.get('symbol_id')
# ))

# try:
#     if 'cursor' in locals():
#         cursor.close()
#         cursor = conn.cursor()

#     try:
#         while cursor.nextset():
#             pass
#     except:
#         pass
    
#     query = """
#         insert into forecast_cache
#         (location_id, forecast_time, temp, precip, humidity, wind_speed, wind_gust, wind_dir, dew_point, pressure, global_rad, symbol_id)
#         VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
#         on duplicate key update
#         temp = values(temp),
#         precip = values(precip),
#         humidity = values(humidity),
#         wind_speed = VALUES(wind_speed),
#         wind_gust = VALUES(wind_gust),
#         wind_dir = values(wind_dir),
#         dew_point = VALUES(dew_point),
#         pressure = VALUES(pressure),
#         global_rad = VALUES(global_rad),
#         symbol_id = VALUES(symbol_id);
#     """

#     cursor.executemany(query, data)
#     conn.commit()
#     print("succeed")

# except Exception as e:
#     print(f"error: {e}")
#     conn.rollback()

precip: 0.0
precip: 0.0
precip: 0.1
precip: 0.1
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.1
precip: 0.1
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.1
precip: 0.1
precip: 0.2
precip: 0.3
precip: 0.3
precip: 0.3
precip: 0.2
precip: 0.1
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.3
precip: 2.1
precip: 1.2
precip: 0.5
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.3
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.0
precip: 0.6
precip: 0.0
precip: 1.6
precip: 0.0
precip: 0.0
precip: 0.0

### **Convert regions to lat/lng via API**

In [55]:
# pip install geopy
from geopy.geocoders import Nominatim
from geopy.exc import GeocoderTimedOut, GeocoderServiceError

In [56]:
geolocator = Nominatim(user_agent="NORA_project")
try:
    location = geolocator.geocode("Carlow, Ireland", addressdetails=True) # dictionary
    if location:
        lat = location.latitude
        lng = location.longitude
        address = location.raw.get('address', {})
        county = address.get('county') or address.get('city') or address.get('town')
        #print(county)
        clean_county = county.replace('County ', '')
        pin_list = [{'region': clean_county, 'lat': lat, 'lng': lng, 'selectable': 'True'}]
    else:
        print("not found")

except (GeocoderTimeOut, GeocoderServiceError) as e:
    print(f"Geocoding error: {e}")

In [57]:
pin_list = pd.DataFrame(pin_list)
try:
    pin_list.to_sql('pins', con=db_conn, if_exists='append', index=False)
    print("succeed")
except Exception as e:
    print(f"error: {e}")

error: Execution failed on sql 'INSERT INTO pins (region, lat, lng, selectable) VALUES (:region, :lat, :lng, :selectable)': (pymysql.err.IntegrityError) (1062, "Duplicate entry '52.8408344--6.9261131' for key 'pins.PRIMARY'")
[SQL: INSERT INTO pins (region, lat, lng, selectable) VALUES (%(region)s, %(lat)s, %(lng)s, %(selectable)s)]
[parameters: {'region': 'Carlow', 'lat': 52.8408344, 'lng': -6.9261131, 'selectable': 'True'}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)