In [188]:
import pandas as pd
import requests, pandas as pd
import xmltodict
import os
from dotenv import load_dotenv
from sqlalchemy import create_engine

In [189]:
load_dotenv()
db_user = os.getenv('db_user')
db_password = os.getenv('db_password')
db_host = os.getenv('db_host')
db_port = os.getenv('db_port')
db_name = os.getenv('db_name')

In [190]:
db_conn = create_engine(f'mysql+pymysql://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}')

# **Carlow**

In [191]:
file_path = '../data/raw/rainfall_Carlow_daily.csv'

In [192]:
df = pd.read_csv(file_path, skiprows=24)

In [193]:
df['date'] = pd.to_datetime(df['date'])

C:\Users\josr4\AppData\Local\Temp\ipykernel_16760\3532345252.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['date'] = pd.to_datetime(df['date'])

### **Data Extraction (2020-2025)**

In [194]:
start_date = '2020-01-01'
end_date = '2025-12-31'

In [195]:
carlow_rain_recent = (df['date'] >= start_date) & (df['date'] <= end_date)

In [196]:
carlow_filtered = df.loc[carlow_rain_recent]

In [197]:
carlow_filtered = carlow_filtered[['date', 'rain', 'soil', 'smd_wd', 'smd_md', 'smd_pd']]

In [198]:
print(carlow_filtered)

           date rain   soil smd_wd smd_md smd_pd
5912 2020-01-01  0.0  5.925    2.5    2.5   -5.1
5913 2020-01-02  2.2  7.728    0.9    0.9   -6.4
5914 2020-01-03  0.1  5.680    1.0    1.0   -6.0
5915 2020-01-04  0.1  6.012    1.2    1.2   -5.5
5916 2020-01-05  0.3  7.295    1.4    1.4   -5.0
...         ...  ...    ...    ...    ...    ...
8099 2025-12-27  0.0  2.266    0.5    0.5   -7.3
8100 2025-12-28  0.0  3.218    0.8    0.8   -6.6
8101 2025-12-29  0.0  3.893    1.1    1.1   -6.0
8102 2025-12-30  0.0  4.752    1.5    1.5   -5.3
8103 2025-12-31  0.0  4.356    1.8    1.8   -4.8

[2192 rows x 6 columns]

In [199]:
carlow_filtered['location'] = 'Carlow'

In [200]:
carlow_filtered = carlow_filtered.rename(columns= {
    'rain': 'rainfall',
    'soil': 'soil_temp'
})
carlow_filtered

           date rainfall soil_temp smd_wd smd_md smd_pd location
5912 2020-01-01      0.0     5.925    2.5    2.5   -5.1   Carlow
5913 2020-01-02      2.2     7.728    0.9    0.9   -6.4   Carlow
5914 2020-01-03      0.1     5.680    1.0    1.0   -6.0   Carlow
5915 2020-01-04      0.1     6.012    1.2    1.2   -5.5   Carlow
5916 2020-01-05      0.3     7.295    1.4    1.4   -5.0   Carlow
...         ...      ...       ...    ...    ...    ...      ...
8099 2025-12-27      0.0     2.266    0.5    0.5   -7.3   Carlow
8100 2025-12-28      0.0     3.218    0.8    0.8   -6.6   Carlow
8101 2025-12-29      0.0     3.893    1.1    1.1   -6.0   Carlow
8102 2025-12-30      0.0     4.752    1.5    1.5   -5.3   Carlow
8103 2025-12-31      0.0     4.356    1.8    1.8   -4.8   Carlow

[2192 rows x 7 columns]

In [201]:
carlow_filtered = carlow_filtered[['location', 'date', 'rainfall', 'smd_wd', 'smd_md', 'smd_pd', 'soil_temp']]
carlow_filtered

     location       date rainfall smd_wd smd_md smd_pd soil_temp
5912   Carlow 2020-01-01      0.0    2.5    2.5   -5.1     5.925
5913   Carlow 2020-01-02      2.2    0.9    0.9   -6.4     7.728
5914   Carlow 2020-01-03      0.1    1.0    1.0   -6.0     5.680
5915   Carlow 2020-01-04      0.1    1.2    1.2   -5.5     6.012
5916   Carlow 2020-01-05      0.3    1.4    1.4   -5.0     7.295
...       ...        ...      ...    ...    ...    ...       ...
8099   Carlow 2025-12-27      0.0    0.5    0.5   -7.3     2.266
8100   Carlow 2025-12-28      0.0    0.8    0.8   -6.6     3.218
8101   Carlow 2025-12-29      0.0    1.1    1.1   -6.0     3.893
8102   Carlow 2025-12-30      0.0    1.5    1.5   -5.3     4.752
8103   Carlow 2025-12-31      0.0    1.8    1.8   -4.8     4.356

[2192 rows x 7 columns]

### **Store Data to db**

In [202]:
try:
    carlow_filtered.to_sql('obs_hist', con=db_conn, if_exists='append', index=False)
    print("succeed")
except Exception as e:
    print(f"error: {e}")

error: Execution failed on sql 'INSERT INTO obs_hist (location, date, rainfall, smd_wd, smd_md, smd_pd, soil_temp) VALUES (:location, :date, :rainfall, :smd_wd, :smd_md, :smd_pd, :soil_temp)': (pymysql.err.IntegrityError) (1062, "Duplicate entry 'Carlow-2020-01-01' for key 'PRIMARY'")
[SQL: INSERT INTO obs_hist (location, date, rainfall, smd_wd, smd_md, smd_pd, soil_temp) VALUES (%(location)s, %(date)s, %(rainfall)s, %(smd_wd)s, %(smd_md)s, %(smd_pd)s, %(soil_temp)s)]
[parameters: [{'location': 'Carlow', 'date': datetime.datetime(2020, 1, 1, 0, 0), 'rainfall': '0.0', 'smd_wd': '2.5', 'smd_md': '2.5', 'smd_pd': '-5.1', 'soil_temp': '5.925'}, {'location': 'Carlow', 'date': datetime.datetime(2020, 1, 2, 0, 0), 'rainfall': '2.2', 'smd_wd': '0.9', 'smd_md': '0.9', 'smd_pd': '-6.4', 'soil_temp': '7.728'}, {'location': 'Carlow', 'date': datetime.datetime(2020, 1, 3, 0, 0), 'rainfall': '0.1', 'smd_wd': '1.0', 'smd_md': '1.0', 'smd_pd': '-6.0', 'soil_temp': '5.680'}, {'location': 'Carlow', 'date': datetime.datetime(2020, 1, 4, 0, 0), 'rainfall': '0.1', 'smd_wd': '1.2', 'smd_md': '1.2', 'smd_pd': '-5.5', 'soil_temp': '6.012'}, {'location': 'Carlow', 'date': datetime.datetime(2020, 1, 5, 0, 0), 'rainfall': '0.3', 'smd_wd': '1.4', 'smd_md': '1.4', 'smd_pd': '-5.0', 'soil_temp': '7.295'}, {'location': 'Carlow', 'date': datetime.datetime(2020, 1, 6, 0, 0), 'rainfall': '10.7', 'smd_wd': '0.0', 'smd_md': '-8.9', 'smd_pd': '-10.0', 'soil_temp': '7.048'}, {'location': 'Carlow', 'date': datetime.datetime(2020, 1, 7, 0, 0), 'rainfall': '0.1', 'smd_wd': '0.7', 'smd_md': '0.7', 'smd_pd': '-8.8', 'soil_temp': '8.009'}, {'location': 'Carlow', 'date': datetime.datetime(2020, 1, 8, 0, 0), 'rainfall': '6.1', 'smd_wd': '0.0', 'smd_md': '-5.0', 'smd_pd': '-10.0', 'soil_temp': '7.143'}  ... displaying 10 of 2192 total bound parameter sets ...  {'location': 'Carlow', 'date': datetime.datetime(2025, 12, 30, 0, 0), 'rainfall': '0.0', 'smd_wd': '1.5', 'smd_md': '1.5', 'smd_pd': '-5.3', 'soil_temp': '4.752'}, {'location': 'Carlow', 'date': datetime.datetime(2025, 12, 31, 0, 0), 'rainfall': '0.0', 'smd_wd': '1.8', 'smd_md': '1.8', 'smd_pd': '-4.8', 'soil_temp': '4.356'}]]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

### **Checking Missing Data**

In [203]:
print(carlow_filtered.isnull().sum())

location     0
date         0
rainfall     0
smd_wd       0
smd_md       0
smd_pd       0
soil_temp    0
dtype: int64

## **Fetching Data via API**

## **1.   Environmental Parameters**

### **1.1   Checking River Codes near Carlow**

In [204]:
endp = "https://wfdapi.edenireland.ie/api/charts/catchments"

In [ ]:
r = requests.get(endp, timeout = 30)
r.raise_for_status() # HTTP success or exception

In [ ]:
data = r.json()
data

{'Success': True,
 'Count': 46,
 'Model': [{'Name': 'Foyle', 'Code': '01', 'Id': 1},
  {'Name': 'Lough Neagh & Lower Bann', 'Code': '03', 'Id': 2},
  {'Name': 'Newry, Fane, Glyde and Dee', 'Code': '06', 'Id': 3},
  {'Name': 'Boyne', 'Code': '07', 'Id': 4},
  {'Name': 'Nanny-Delvin', 'Code': '08', 'Id': 5},
  {'Name': 'Liffey and Dublin Bay', 'Code': '09', 'Id': 6},
  {'Name': 'Ovoca-Vartry', 'Code': '10', 'Id': 7},
  {'Name': 'Owenavorragh', 'Code': '11', 'Id': 8},
  {'Name': 'Slaney & Wexford Harbour', 'Code': '12', 'Id': 9},
  {'Name': 'Ballyteigue-Bannow', 'Code': '13', 'Id': 10},
  {'Name': 'Barrow', 'Code': '14', 'Id': 11},
  {'Name': 'Nore', 'Code': '15', 'Id': 12},
  {'Name': 'Suir', 'Code': '16', 'Id': 13},
  {'Name': 'Colligan-Mahon', 'Code': '17', 'Id': 14},
  {'Name': 'Blackwater (Munster)', 'Code': '18', 'Id': 15},
  {'Name': 'Lee, Cork Harbour and Youghal Bay', 'Code': '19', 'Id': 16},
  {'Name': 'Bandon-Ilen', 'Code': '20', 'Id': 17},
  {'Name': 'Dunmanus-Bantry-Kenmare', 'Code': '21', 'Id': 18},
  {'Name': 'Laune-Maine-Dingle Bay', 'Code': '22', 'Id': 19},
  {'Name': 'Tralee Bay-Feale', 'Code': '23', 'Id': 20},
  {'Name': 'Shannon Estuary South', 'Code': '24', 'Id': 21},
  {'Name': 'Lower Shannon', 'Code': '25A', 'Id': 22},
  {'Name': 'Lower Shannon', 'Code': '25B', 'Id': 23},
  {'Name': 'Lower Shannon', 'Code': '25C', 'Id': 24},
  {'Name': 'Lower Shannon', 'Code': '25D', 'Id': 25},
  {'Name': 'Upper Shannon', 'Code': '26A', 'Id': 26},
  {'Name': 'Upper Shannon', 'Code': '26B', 'Id': 27},
  {'Name': 'Upper Shannon', 'Code': '26C', 'Id': 28},
  {'Name': 'Upper Shannon', 'Code': '26D', 'Id': 29},
  {'Name': 'Upper Shannon', 'Code': '26E', 'Id': 30},
  {'Name': 'Upper Shannon', 'Code': '26F', 'Id': 31},
  {'Name': 'Upper Shannon', 'Code': '26G', 'Id': 32},
  {'Name': 'Shannon Estuary North', 'Code': '27', 'Id': 33},
  {'Name': 'Mal Bay', 'Code': '28', 'Id': 34},
  {'Name': 'Galway Bay South East', 'Code': '29', 'Id': 35},
  {'Name': 'Corrib', 'Code': '30', 'Id': 36},
  {'Name': 'Galway Bay North', 'Code': '31', 'Id': 37},
  {'Name': 'Erriff-Clew Bay', 'Code': '32', 'Id': 38},
  {'Name': 'Blacksod-Broadhaven', 'Code': '33', 'Id': 39},
  {'Name': 'Moy & Killala Bay', 'Code': '34', 'Id': 40},
  {'Name': 'Sligo Bay & Drowse', 'Code': '35', 'Id': 41},
  {'Name': 'Erne', 'Code': '36', 'Id': 42},
  {'Name': 'Donegal Bay North', 'Code': '37', 'Id': 43},
  {'Name': 'Gweebarra-Sheephaven', 'Code': '38', 'Id': 44},
  {'Name': 'Lough Swilly', 'Code': '39', 'Id': 45},
  {'Name': 'Donagh-Moville', 'Code': '40', 'Id': 46}],
 'Type': 0}

*   **count: 46 catchments**

In [207]:
type(data)

dict

In [208]:
data.keys()

dict_keys(['Success', 'Count', 'Model', 'Type'])

Barrow / Nore / Suir: key catchments in South-East

In [209]:
target = ["Barrow", "Nore", "Suir"]

In [210]:
filtered_target = [item for item in data['Model'] if item['Name'] in target]

In [211]:
filtered_target # Barrow's code: 14

[{'Name': 'Barrow', 'Code': '14', 'Id': 11},
 {'Name': 'Nore', 'Code': '15', 'Id': 12},
 {'Name': 'Suir', 'Code': '16', 'Id': 13}]

*   **Barrow's code: 14**

### **1.2   Barrow's Subcatchment**

In [212]:
endp2 = "https://wfdapi.edenireland.ie/api/catchment/14"

In [213]:
r2 = requests.get(endp2, timeout = 30)
r2.raise_for_status()

In [214]:
data2 = r2.json()
data2

{'Code': '14',
 'Name': 'Barrow',
 'Profile': 'This catchment includes the area drained by the River Barrow upstream of the River Nore confluence and all streams entering tidal water between the Barrow railway bridge at Great Island and Ringwood, Co. Kilkenny, draining a total area of 3,025km². The largest urban centre in the catchment is Carlow. The other main urban centres in this catchment are New Ross, Graiguenamanagh, Athy, Portlaoise, Mountmellick, Portarlington, Monasterevin and Kildare. The total population of the catchment is approximately 188117 with a population density of 62 people per km². The Barrow catchment is underlain in its flat northern area by limestones of varying purity which continue down the western side of the catchment and sustain good groundwater resources in places. On the eastern side of the catchment, granites dominate, culminating in the summits of the Blackstairs Mountains.',
 'Area': 3015.7,
 'GeometryExtent': '230320,114147,289600,234340',
 'LastCycleApproved': 'WFD Cycle 3',
 'Subcatchments': [{'Name': 'Barrow_SC_090',
   'Code': '14_13',
   'Area': 189.01,
   'GeometryExtent': '270560,154000,285000,184875'},
  {'Name': 'Barrow_SC_100',
   'Code': '14_4',
   'Area': 100.43,
   'GeometryExtent': '268338,150386,276220,174660'},
  {'Name': 'Barrow_SC_140',
   'Code': '14_10',
   'Area': 152.67,
   'GeometryExtent': '270657,141700,284280,161060'},
  {'Name': 'Barrow_SC_110',
   'Code': '14_5',
   'Area': 100.5,
   'GeometryExtent': '262360,161780,270725,183580'},
  {'Name': 'Slate_SC_010',
   'Code': '14_16',
   'Area': 215.46,
   'GeometryExtent': '261260,210460,284300,230938'},
  {'Name': 'Lerr_SC_010',
   'Code': '14_6',
   'Area': 111.07,
   'GeometryExtent': '271680,176320,286540,192020'},
  {'Name': 'Greese_SC_010',
   'Code': '14_9',
   'Area': 144.25,
   'GeometryExtent': '271720,182500,289600,203900'},
  {'Name': 'Figile_SC_010',
   'Code': '14_3',
   'Area': 95.22,
   'GeometryExtent': '258720,221860,276197,233996'},
  {'Name': 'Barrow_SC_080',
   'Code': '14_2',
   'Area': 83.85,
   'GeometryExtent': '265840,184640,278120,199760'},
  {'Name': 'Barrow_SC_060',
   'Code': '14_18',
   'Area': 273.36,
   'GeometryExtent': '261274,196855,286920,215620'},
  {'Name': 'Barrow_SC_120',
   'Code': '14_8',
   'Area': 123.11,
   'GeometryExtent': '257740,150380,270690,164940'},
  {'Name': 'Barrow_SC_130',
   'Code': '14_7',
   'Area': 111.93,
   'GeometryExtent': '261920,130374,273820,153647'},
  {'Name': 'Barrow_SC_050',
   'Code': '14_17',
   'Area': 241.2,
   'GeometryExtent': '249820,185680,265947,212417'},
  {'Name': 'Barrow_SC_020',
   'Code': '14_11',
   'Area': 154.56,
   'GeometryExtent': '243960,189280,258270,212861'},
  {'Name': 'Barrow_SC_070',
   'Code': '14_12',
   'Area': 160.83,
   'GeometryExtent': '257880,174109,272007,196855'},
  {'Name': 'Barrow_SC_010',
   'Code': '14_15',
   'Area': 206.45,
   'GeometryExtent': '230320,196920,246470,217660'},
  {'Name': 'Figile_SC_020',
   'Code': '14_14',
   'Area': 206.33,
   'GeometryExtent': '241720,217820,265380,234340'},
  {'Name': 'Barrow_SC_030',
   'Code': '14_1',
   'Area': 58.05,
   'GeometryExtent': '241500,209276,258285,217280'},
  {'Name': 'Barrow_SC_040',
   'Code': '14_20',
   'Area': 129.76,
   'GeometryExtent': '240220,210620,266740,223060'},
  {'Name': 'Barrow_SC_150',
   'Code': '14_19',
   'Area': 157.56,
   'GeometryExtent': '267222,114147,281980,144340'}]}

*   The largest urban catchment in Barrow is Carlow
*   Barrow_SC_060 has the largest area

### **1.3   Water Bodies within Carlow (Barrow Catchment)**

In [227]:
endp3 = "https://wfdapi.edenireland.ie/api/search?v=barrow&size=100"

In [228]:
r3 = requests.get(endp3, timeout = 30)
r3.raise_for_status()

In [229]:
data3 = r3.json()
data3

{'Results': [{'Name': 'Barrow',
   'Type': 'Catchment',
   'Organisation': 'Kildare County Council',
   'Code': '14',
   'GeometryExtent': '230320,114147,289600,234340'},
  {'Name': 'Barrow_SC_030',
   'Type': 'Subcatchment',
   'Organisation': 'Offaly County Council',
   'Code': '14_1',
   'GeometryExtent': '241500,209276,258285,217280'},
  {'Name': 'Barrow_SC_140',
   'Type': 'Subcatchment',
   'Organisation': 'Carlow County Council',
   'Code': '14_10',
   'GeometryExtent': '270657,141700,284280,161060'},
  {'Name': 'Barrow_SC_020',
   'Type': 'Subcatchment',
   'Organisation': 'Laois County Council',
   'Code': '14_11',
   'GeometryExtent': '243960,189280,258270,212861'},
  {'Name': 'Barrow_SC_070',
   'Type': 'Subcatchment',
   'Organisation': 'Laois County Council',
   'Code': '14_12',
   'GeometryExtent': '257880,174109,272007,196855'},
  {'Name': 'Barrow_SC_090',
   'Type': 'Subcatchment',
   'Organisation': 'Carlow County Council',
   'Code': '14_13',
   'GeometryExtent': '270560,154000,285000,184875'},
  {'Name': 'Barrow_SC_010',
   'Type': 'Subcatchment',
   'Organisation': 'Laois County Council',
   'Code': '14_15',
   'GeometryExtent': '230320,196920,246470,217660'},
  {'Name': 'Barrow_SC_050',
   'Type': 'Subcatchment',
   'Organisation': 'Laois County Council',
   'Code': '14_17',
   'GeometryExtent': '249820,185680,265947,212417'},
  {'Name': 'Barrow_SC_060',
   'Type': 'Subcatchment',
   'Organisation': 'Kildare County Council',
   'Code': '14_18',
   'GeometryExtent': '261274,196855,286920,215620'},
  {'Name': 'Barrow_SC_150',
   'Type': 'Subcatchment',
   'Organisation': 'Wexford County Council',
   'Code': '14_19',
   'GeometryExtent': '267222,114147,281980,144340'},
  {'Name': 'Barrow_SC_080',
   'Type': 'Subcatchment',
   'Organisation': 'Kildare County Council',
   'Code': '14_2',
   'GeometryExtent': '265840,184640,278120,199760'},
  {'Name': 'Barrow_SC_040',
   'Type': 'Subcatchment',
   'Organisation': 'Offaly County Council',
   'Code': '14_20',
   'GeometryExtent': '240220,210620,266740,223060'},
  {'Name': 'Barrow_SC_100',
   'Type': 'Subcatchment',
   'Organisation': 'Carlow County Council',
   'Code': '14_4',
   'GeometryExtent': '268338,150386,276220,174660'},
  {'Name': 'Barrow_SC_110',
   'Type': 'Subcatchment',
   'Organisation': 'Carlow County Council',
   'Code': '14_5',
   'GeometryExtent': '262360,161780,270725,183580'},
  {'Name': 'Barrow_SC_130',
   'Type': 'Subcatchment',
   'Organisation': 'Kilkenny County Council',
   'Code': '14_7',
   'GeometryExtent': '261920,130374,273820,153647'},
  {'Name': 'Barrow_SC_120',
   'Type': 'Subcatchment',
   'Organisation': 'Kilkenny County Council',
   'Code': '14_8',
   'GeometryExtent': '257740,150380,270690,164940'},
  {'Name': 'Grand Canal Barrow Line (Barrow)',
   'Type': 'River',
   'Organisation': 'Kildare County Council',
   'Code': 'IE_14_AWB_GCBL',
   'GeometryExtent': '260682,193458,277922,225588'},
  {'Name': 'Grand Canal Milltown Feeder (Barrow)',
   'Type': 'River',
   'Organisation': 'Kildare County Council',
   'Code': 'IE_14_AWB_GCMF',
   'GeometryExtent': '274769,215500,277237,224447'},
  {'Name': 'Grand Canal Main Line East (Barrow)',
   'Type': 'River',
   'Organisation': 'Kildare County Council',
   'Code': 'IE_14_AWB_GCMLE',
   'GeometryExtent': '268758,224968,281956,230683'},
  {'Name': 'Grand Canal Main Line West (Barrow)',
   'Type': 'River',
   'Organisation': 'Kildare County Council',
   'Code': 'IE_14_AWB_GCMLW',
   'GeometryExtent': '244171,227220,254820,232047'},
  {'Name': 'Barrow Suir Nore Estuary',
   'Type': 'Transitional',
   'Organisation': 'Wexford County Council',
   'Code': 'IE_SE_100_0100',
   'GeometryExtent': '268422,103288,275096,115982'},
  {'Name': 'Barrow Nore Estuary Upper',
   'Type': 'Transitional',
   'Organisation': 'Wexford County Council',
   'Code': 'IE_SE_100_0250',
   'GeometryExtent': '270604,127364,272238,130565'},
  {'Name': 'Upper Barrow Estuary',
   'Type': 'Transitional',
   'Organisation': 'Kilkenny County Council',
   'Code': 'IE_SE_100_0300',
   'GeometryExtent': '270718,130299,273943,139475'},
  {'Name': 'BARROW_010',
   'Type': 'River',
   'Organisation': 'Laois County Council',
   'Code': 'IE_SE_14B010060',
   'GeometryExtent': '231121,204428,237216,211039'},
  {'Name': 'BARROW_020',
   'Type': 'River',
   'Organisation': 'Laois County Council',
   'Code': 'IE_SE_14B010200',
   'GeometryExtent': '234472,210790,238685,215113'},
  {'Name': 'BARROW_030',
   'Type': 'River',
   'Organisation': 'Laois County Council',
   'Code': 'IE_SE_14B010300',
   'GeometryExtent': '237648,208307,243395,215546'},
  {'Name': 'BARROW_040',
   'Type': 'River',
   'Organisation': 'Laois County Council',
   'Code': 'IE_SE_14B010500',
   'GeometryExtent': '237880,206025,246470,212318'},
  {'Name': 'BARROW_050',
   'Type': 'River',
   'Organisation': 'Laois County Council',
   'Code': 'IE_SE_14B010550',
   'GeometryExtent': '246264,204594,250369,210087'},
  {'Name': 'BARROW_060',
   'Type': 'River',
   'Organisation': 'Laois County Council',
   'Code': 'IE_SE_14B010700',
   'GeometryExtent': '247748,208181,253684,211641'},
  {'Name': 'BARROW_070',
   'Type': 'River',
   'Organisation': 'Offaly County Council',
   'Code': 'IE_SE_14B010780',
   'GeometryExtent': '250847,210749,254340,212861'},
  {'Name': 'BARROW_080',
   'Type': 'River',
   'Organisation': 'Laois County Council',
   'Code': 'IE_SE_14B010900',
   'GeometryExtent': '254340,212085,258270,212840'},
  {'Name': 'BARROW_090',
   'Type': 'River',
   'Organisation': 'Laois County Council',
   'Code': 'IE_SE_14B011000',
   'GeometryExtent': '258270,210620,262357,212417'},
  {'Name': 'BARROW_100',
   'Type': 'River',
   'Organisation': 'Kildare County Council',
   'Code': 'IE_SE_14B011130',
   'GeometryExtent': '262357,208905,265196,210745'},
  {'Name': 'BARROW_110',
   'Type': 'River',
   'Organisation': 'Laois County Council',
   'Code': 'IE_SE_14B011300',
   'GeometryExtent': '259797,205718,264343,210150'},
  {'Name': 'BARROW_120',
   'Type': 'River',
   'Organisation': 'Kildare County Council',
   'Code': 'IE_SE_14B011500',
   'GeometryExtent': '259229,196855,268155,209088'},
  {'Name': 'BARROW_130',
   'Type': 'River',
   'Organisation': 'Kildare County Council',
   'Code': 'IE_SE_14B011600',
   'GeometryExtent': '265943,192680,268622,196855'},
  {'Name': 'BARROW_140',
   'Type': 'River',
   'Organisation': 'Kildare County Council',
   'Code': 'IE_SE_14B011900',
   'GeometryExtent': '264297,188160,270382,194346'},
  {'Name': 'BARROW_150',
   'Type': 'River',
   'Organisation': 'Kildare County Council',
   'Code': 'IE_SE_14B012000',
   'GeometryExtent': '270351,184696,274687,191896'},
  {'Name': 'BARROW_160',
   'Type': 'River',
   'Organisation': 'Laois County Council',
   'Code': 'IE_SE_14B012460',
   'GeometryExtent': '268267,174109,273289,185580'},
  {'Name': 'BARROW_170',
   'Type': 'River',
   'Organisation': 'Carlow County Council',
   'Code': 'IE_SE_14B012600',
   'GeometryExtent': '266857,170420,271021,177834'},
  {'Name': 'BARROW_180',
   'Type': 'River',
   'Organisation': 'Carlow County Council',
   'Code': 'IE_SE_14B012700',
   'GeometryExtent': '266975,165435,274998,172502'},
  {'Name': 'BARROW_190',
   'Type': 'River',
   'Organisation': 'Carlow County Council',
   'Code': 'IE_SE_14B012820',
   'GeometryExtent': '265791,162300,270725,165435'},
  {'Name': 'BARROW_200',
   'Type': 'River',
   'Organisation': 'Carlow County Council',
   'Code': 'IE_SE_14B012920',
   'GeometryExtent': '268920,161313,274492,163881'},
  {'Name': 'BARROW_210',
   'Type': 'River',
   'Organisation': 'Carlow County Council',
   'Code': 'IE_SE_14B013100',
   'GeometryExtent': '265480,153255,272890,161421'},
  {'Name': 'BARROW_220',
   'Type': 'River',
   'Organisation': 'Carlow County Council',
   'Code': 'IE_SE_14B013300',
   'GeometryExtent': '268475,150146,271424,153647'},
  {'Name': 'BARROW_230',
   'Type': 'River',
   'Organisation': 'Kilkenny County Council',
   'Code': 'IE_SE_14B013514',
   'GeometryExtent': '268755,142136,275221,150386'},
  {'Name': 'BARROW_240',
   'Type': 'River',
   'Organisation': 'Kilkenny County Council',
   'Code': 'IE_SE_14B013600',
   'GeometryExtent': '271023,139313,272477,143378'},
  {'Name': 'Barrowen Emlaghkeeragh',
   'Type': 'Lake',
   'Organisation': 'Galway County Council',
   'Code': 'IE_WE_31_183',
   'GeometryExtent': '65048.5,242197,66567.1,244071'}],
 'Page': 0,
 'Size': 100,
 'Total': 48}

In [230]:
results = [ r for r in data3["Results"] if r["Type"] == "River"and r["Organisation"] == "Carlow County Council"]
results

[{'Name': 'BARROW_170',
  'Type': 'River',
  'Organisation': 'Carlow County Council',
  'Code': 'IE_SE_14B012600',
  'GeometryExtent': '266857,170420,271021,177834'},
 {'Name': 'BARROW_180',
  'Type': 'River',
  'Organisation': 'Carlow County Council',
  'Code': 'IE_SE_14B012700',
  'GeometryExtent': '266975,165435,274998,172502'},
 {'Name': 'BARROW_190',
  'Type': 'River',
  'Organisation': 'Carlow County Council',
  'Code': 'IE_SE_14B012820',
  'GeometryExtent': '265791,162300,270725,165435'},
 {'Name': 'BARROW_200',
  'Type': 'River',
  'Organisation': 'Carlow County Council',
  'Code': 'IE_SE_14B012920',
  'GeometryExtent': '268920,161313,274492,163881'},
 {'Name': 'BARROW_210',
  'Type': 'River',
  'Organisation': 'Carlow County Council',
  'Code': 'IE_SE_14B013100',
  'GeometryExtent': '265480,153255,272890,161421'},
 {'Name': 'BARROW_220',
  'Type': 'River',
  'Organisation': 'Carlow County Council',
  'Code': 'IE_SE_14B013300',
  'GeometryExtent': '268475,150146,271424,153647'}]

In [231]:
len(results)

6

*   **Identified 6 river segments of the Barrow catchment within Carlow**

### **1.4   Identification of Segments for Future Iteration**

In [232]:
endp4 = "https://wfdapi.edenireland.ie/api/waterbody/IE_SE_14B012600"

In [233]:
r4 = requests.get(endp4, timeout = 30)
r4.raise_for_status()

In [234]:
data4 = r4.json()
data4

{'Catchment': [{'Name': 'Barrow', 'Code': '14'}],
 'Subcatchment': [{'Name': 'Barrow_SC_100', 'Code': '14_4'},
  {'Name': 'Barrow_SC_110', 'Code': '14_5'}],
 'Code': 'IE_SE_14B012600',
 'Name': 'BARROW_170',
 'LocalAuthority': 'Carlow County Council',
 'Type': 'River',
 'Rbd': 'South Eastern',
 'Tier1Risk': 'At risk',
 'ProtectedArea': None,
 'ArtificialName': None,
 'ModifiedName': None,
 'Easting': 269004.41,
 'Northing': 174009.61,
 'Latitude': 52.8130078,
 'Longitude': -6.9773591,
 'GeometryExtent': '266857,170420,271021,177834',
 'Status': [{'Code': 'SW 2007-2009',
   'Status': [{'Status': 'Moderate',
     'Name': 'Ecological Status or Potential',
     'Id': '82c44189-7fb3-e411-b3b4-0050568a69e2',
     'ParentId': None,
     'AssessmentTechnique': 'Monitoring',
     'StatusConfidence': 'no information or unknown'},
    {'Status': 'Moderate',
     'Name': 'Biological Status or Potential',
     'Id': '354c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '82c44189-7fb3-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Moderate',
     'Name': 'Invertebrate Status or Potential',
     'Id': '434c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '354c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Supporting Chemistry Conditions',
     'Id': '4b4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '82c44189-7fb3-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'General Conditions',
     'Id': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4b4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Oxygenation Conditions',
     'Id': '554c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Acidification Conditions',
     'Id': '5d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'pH',
     'Id': '5f4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '5d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Nutrient Conditions',
     'Id': '634c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Fail',
     'Name': 'Nitrogen Conditions',
     'Id': '0a226dd5-7310-e711-9f02-0050568a69e2',
     'ParentId': '634c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Fail',
     'Name': 'Nitrate',
     'Id': '674c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '0a226dd5-7310-e711-9f02-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Ammonium',
     'Id': '6b4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '0a226dd5-7310-e711-9f02-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Phosphorous Conditions',
     'Id': 'f07240df-7310-e711-9f02-0050568a69e2',
     'ParentId': '634c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Orthophosphate',
     'Id': '6f4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': 'f07240df-7310-e711-9f02-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''}],
   'Failures': [],
   'HasFailures': False},
  {'Code': 'SW 2010-2012',
   'Status': [{'Status': 'Moderate',
     'Name': 'Ecological Status or Potential',
     'Id': '82c44189-7fb3-e411-b3b4-0050568a69e2',
     'ParentId': None,
     'AssessmentTechnique': 'Monitoring',
     'StatusConfidence': 'no information or unknown'},
    {'Status': 'Moderate',
     'Name': 'Biological Status or Potential',
     'Id': '354c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '82c44189-7fb3-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Moderate',
     'Name': 'Invertebrate Status or Potential',
     'Id': '434c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '354c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Supporting Chemistry Conditions',
     'Id': '4b4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '82c44189-7fb3-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'General Conditions',
     'Id': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4b4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Oxygenation Conditions',
     'Id': '554c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Acidification Conditions',
     'Id': '5d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'pH',
     'Id': '5f4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '5d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Nutrient Conditions',
     'Id': '634c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Moderate',
     'Name': 'Nitrogen Conditions',
     'Id': '0a226dd5-7310-e711-9f02-0050568a69e2',
     'ParentId': '634c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Moderate',
     'Name': 'Nitrate',
     'Id': '674c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '0a226dd5-7310-e711-9f02-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'High',
     'Name': 'Ammonium',
     'Id': '6b4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '0a226dd5-7310-e711-9f02-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'High',
     'Name': 'Phosphorous Conditions',
     'Id': 'f07240df-7310-e711-9f02-0050568a69e2',
     'ParentId': '634c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'High',
     'Name': 'Orthophosphate',
     'Id': '6f4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': 'f07240df-7310-e711-9f02-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''}],
   'Failures': [],
   'HasFailures': False},
  {'Code': 'SW 2010-2015',
   'Status': [{'Status': 'Moderate',
     'Name': 'Ecological Status or Potential',
     'Id': '82c44189-7fb3-e411-b3b4-0050568a69e2',
     'ParentId': None,
     'AssessmentTechnique': 'Monitoring',
     'StatusConfidence': 'high confidence'},
    {'Status': 'Moderate',
     'Name': 'Biological Status or Potential',
     'Id': '354c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '82c44189-7fb3-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Moderate',
     'Name': 'Invertebrate Status or Potential',
     'Id': '434c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '354c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Supporting Chemistry Conditions',
     'Id': '4b4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '82c44189-7fb3-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'General Conditions',
     'Id': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4b4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Oxygenation Conditions',
     'Id': '554c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Dissolved Oxygen (% Sat)',
     'Id': '574c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '554c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'High',
     'Name': 'Other determinand for oxygenation conditions',
     'Id': '5b4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '554c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Acidification Conditions',
     'Id': '5d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'pH',
     'Id': '5f4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '5d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Nutrient Conditions',
     'Id': '634c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Moderate',
     'Name': 'Nitrogen Conditions',
     'Id': '0a226dd5-7310-e711-9f02-0050568a69e2',
     'ParentId': '634c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Moderate',
     'Name': 'Nitrate',
     'Id': '674c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '0a226dd5-7310-e711-9f02-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'High',
     'Name': 'Ammonium',
     'Id': '6b4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '0a226dd5-7310-e711-9f02-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'High',
     'Name': 'Phosphorous Conditions',
     'Id': 'f07240df-7310-e711-9f02-0050568a69e2',
     'ParentId': '634c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'High',
     'Name': 'Orthophosphate',
     'Id': '6f4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': 'f07240df-7310-e711-9f02-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''}],
   'Failures': [],
   'HasFailures': False},
  {'Code': 'SW 2013-2018',
   'Status': [{'Status': 'Moderate',
     'Name': 'Ecological Status or Potential',
     'Id': '82c44189-7fb3-e411-b3b4-0050568a69e2',
     'ParentId': None,
     'AssessmentTechnique': 'Monitoring',
     'StatusConfidence': 'high confidence'},
    {'Status': 'Moderate',
     'Name': 'Biological Status or Potential',
     'Id': '354c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '82c44189-7fb3-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Moderate',
     'Name': 'Invertebrate Status or Potential',
     'Id': '434c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '354c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Supporting Chemistry Conditions',
     'Id': '4b4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '82c44189-7fb3-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'General Conditions',
     'Id': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4b4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Oxygenation Conditions',
     'Id': '554c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Dissolved Oxygen (% Sat)',
     'Id': '574c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '554c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'High',
     'Name': 'Other determinand for oxygenation conditions',
     'Id': '5b4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '554c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Acidification Conditions',
     'Id': '5d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'pH',
     'Id': '5f4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '5d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Nutrient Conditions',
     'Id': '634c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Moderate',
     'Name': 'Nitrogen Conditions',
     'Id': '0a226dd5-7310-e711-9f02-0050568a69e2',
     'ParentId': '634c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Moderate',
     'Name': 'Nitrate',
     'Id': '674c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '0a226dd5-7310-e711-9f02-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'High',
     'Name': 'Ammonium',
     'Id': '6b4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '0a226dd5-7310-e711-9f02-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'High',
     'Name': 'Phosphorous Conditions',
     'Id': 'f07240df-7310-e711-9f02-0050568a69e2',
     'ParentId': '634c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'High',
     'Name': 'Orthophosphate',
     'Id': '6f4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': 'f07240df-7310-e711-9f02-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''}],
   'Failures': [],
   'HasFailures': False},
  {'Code': 'SW 2016-2021',
   'Status': [{'Status': 'Moderate',
     'Name': 'Ecological Status or Potential',
     'Id': '82c44189-7fb3-e411-b3b4-0050568a69e2',
     'ParentId': None,
     'AssessmentTechnique': 'Monitoring',
     'StatusConfidence': 'high confidence'},
    {'Status': 'Moderate',
     'Name': 'Biological Status or Potential',
     'Id': '354c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '82c44189-7fb3-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Moderate',
     'Name': 'Invertebrate Status or Potential',
     'Id': '434c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '354c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Supporting Chemistry Conditions',
     'Id': '4b4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '82c44189-7fb3-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'General Conditions',
     'Id': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4b4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Oxygenation Conditions',
     'Id': '554c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Dissolved Oxygen (% Sat)',
     'Id': '574c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '554c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'High',
     'Name': 'Other determinand for oxygenation conditions',
     'Id': '5b4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '554c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Acidification Conditions',
     'Id': '5d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'pH',
     'Id': '5f4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '5d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Nutrient Conditions',
     'Id': '634c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Moderate',
     'Name': 'Nitrogen Conditions',
     'Id': '0a226dd5-7310-e711-9f02-0050568a69e2',
     'ParentId': '634c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Moderate',
     'Name': 'Nitrate',
     'Id': '674c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '0a226dd5-7310-e711-9f02-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'High',
     'Name': 'Ammonium',
     'Id': '6b4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '0a226dd5-7310-e711-9f02-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'High',
     'Name': 'Phosphorous Conditions',
     'Id': 'f07240df-7310-e711-9f02-0050568a69e2',
     'ParentId': '634c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'High',
     'Name': 'Orthophosphate',
     'Id': '6f4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': 'f07240df-7310-e711-9f02-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''}],
   'Failures': [],
   'HasFailures': False},
  {'Code': 'SW 2019-2024',
   'Status': [{'Status': 'Moderate',
     'Name': 'Ecological Status or Potential',
     'Id': '82c44189-7fb3-e411-b3b4-0050568a69e2',
     'ParentId': None,
     'AssessmentTechnique': 'Monitoring',
     'StatusConfidence': 'medium confidence'},
    {'Status': 'Moderate',
     'Name': 'Biological Status or Potential',
     'Id': '354c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '82c44189-7fb3-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Moderate',
     'Name': 'Invertebrate Status or Potential',
     'Id': '434c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '354c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Supporting Chemistry Conditions',
     'Id': '4b4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '82c44189-7fb3-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'General Conditions',
     'Id': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4b4c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'AssessmentTechnique': '',
     'StatusConfidence': ''},
    {'Status': 'Pass',
     'Name': 'Oxygenation Conditions',
     'Id': '554c8aa9-d3ef-e411-b3b4-0050568a69e2',
     'ParentId': '4d4c8aa9-d3ef-e411-b3b4-0050568a69e2',

## **2.   Rainfall Forecast**

In [223]:
lat, lon = 52.841, -6.926
endp5 = f"http://openaccess.pf.api.met.ie/metno-wdb2ts/locationforecast?lat={lat};long={lon}"

r5 = requests.get(endp5)

In [224]:
data5 = xmltodict.parse(r5.text)
print(data5.keys())

dict_keys(['weatherdata'])

In [226]:
forecast_data = data5['weatherdata']